### PR TITLE
Add missing field linkNewTab

### PR DESCRIPTION
**Pull request by nicoanders**
## Changes

Adds the field "linkNewTab" to be in sync with the according PHP definition

### Checklist

- [ ] the [list of features](docs/guide/FEATURELIST.md) is updated (if it's a feature and it's relevant)
- [x] I followed [contributing](https://github.com/DivanteLtd/shopware-pwa/blob/master/CONTRIBUTING.md) guidelines

### CODE REVIEW

**Review by mkucmus — CHANGES_REQUESTED** [review]
thanks, feel free to add all the missing fields they are left and not appear here so far 👍🏻 

one little change here: the `linkNewTab` field is also `null` by default.

**Comment by nicoanders** [comment]
Hi @mkucmus,
sure you're right, regarding the default values and I will correct it anyway...
But I had a closer look on the interfaces and now I'm not sure if it's better placed by context here https://github.com/vuestorefront/shopware-pwa/blob/master/packages/commons/interfaces/models/content/navigation/Navigation.ts#L47
Maybe extending from the interface also makes sense, because they are very similar.
What do you think?

**Comment by mkucmus** [comment]
> Hi @mkucmus, sure you're right, regarding the default values and I will correct it anyway... But I had a closer look on the interfaces and now I'm not sure if it's better placed by context here https://github.com/vuestorefront/shopware-pwa/blob/master/packages/commons/interfaces/models/content/navigation/Navigation.ts#L47 Maybe extending from the interface also makes sense, because they are very similar. What do you think?

It's always good to generalize some types and use inheritance to reduce the codesize. Go ahead if you can!

**Review by mkucmus — APPROVED** [review]
thanks! we will be developing that on the occasion ;)

**Pull request merged**
