### PR TITLE
fix(composables): product available stock information

### LINKED ISSUE #1539: [BUG] CustomFields are moved
### Describe the bug
The customFields are not available in the response object. I have this problem since i updated to pwa version 0.9.0.
in 0.8.2 i could get them from the translated object in a response.

I have a temporary solution by adding this to the `shopware-pwa.config.js` file:

```js
module.exports = {
  shopwareEndpoint: 'SECERT',
  shopwareAccessToken: 'SECRET',
  pwaHost: 'SECRET',
  apiDefaults: {
    useCms: {
      limit: 18,
      includes: {
        product: ['customFields', 'media'],
      },
    },
    useListing: {
      limit: 18,
    },
    useProduct: {
      includes: {
        product: ['customFields'],
      },
    },
    useNavigation: {
      includes: {
        category: ['customFields'],
      },
    },
  },
}
```

But with this solution i will get 2 customFields Objects in every response. This is the response with configuration above:

```json
{
  "product": {
    "name": null,
    "description": null,
    "manufacturer": null,
    "customFields": {
      "borg_id": "7bd89b026b5642dda7ba8a27433dcec9",
      "usp_active": true,
      "borg_active": true,
      "usp_content": "Best verkocht!",
      "borg_required": "1",
      "custom_delivery": "delivery",
      "product_custom_field_title": "Gebruiksaanwijzing",
      "product_custom_field_video": "https://youtu.be/-JMAj6dgGso",
      "product_custom_field_usp_list": "{\"0\":{\"icon\":\"egg\",\"usp\":\"Geen eieren\"},\"1\":{\"icon\":\"check\",\"usp\":\"Lekkerste Kip van Nederland\"},\"2\":{\"icon\":\"check\",\"usp\":\"Lekkerste Kip van Nederland\"},\"3\":{\"icon\":\"check\",\"usp\":\"Lekkerste Kip van Nederland\"}}",
      "custom_delivery_available_fields": [
        "757b981b517e4cb59e63b2dbfad46cf9",
        "a4139c276ad24bf1ab51cebce3864376"
      ],
      "product_custom_field_button_text": "Meer Info",
      "product_custom_field_text_content": "<b>Hoe werkt de Kippiepan?</b><div>De Kippiepan is een pan die aangesloten kan worden op netstroom om de inhoud op te warmen. Er zijn verschillende varianten verkrijgbaar via onze webshop en in al onze winkels. Voor de elektrische pannen wordt borg betaalt, maar klanten kunnen er ook voor kiezen om de pan thuis te houden voor dat bedrag.</div><div>De Kippiepan is erg eenvoudig in gebruik. Na het verwijderen van de doorzichtige plastic deksel, steek je de stekker van de pan in het stopcontact. Op stand nummer 2 laat je de pan ongeveer 30 minuten opwarmen. Let er op dat je de inhoud af en toe goed doorroert of omschept. Dit om aanbakken te voorkomen. Absoluut geen gedoe of stress in de keuken. Klaar? Aanschuiven maar!</div><div><i style=\"letter-spacing: 0px;\">Tip: wordt de inhoud van de Kippiepan niet snel genoeg warm? Zet de thermostaat gerust een stand hoger. Blijf wel goed omroeren of omscheppen om aanbakken te voorkomen.</i><br></div><div><i style=\"letter-spacing: 0px;\"><br></i></div><div><b style=\"letter-spacing: 0px;\">Heb je een losse aluminium schaal met inhoud besteld? Deze kan ook in de oven worden opgewarmd! Haal de plastic deksel van de schaal af en plaats de aluminiumschaal in een voorverwarmde oven. Ongeveer 15 tot 20 minuten op 180 graden is voldoende.</b></div><div><b style=\"letter-spacing: 0px;\"><br></b></div><div><b style=\"letter-spacing: 0px;\">Exclusief bij Kippie:</b><span style=\"letter-spacing: 0px;\"> de inhoud van iedere Kippiepan wordt in een aluminiumschaal met plastic deksel in de Kippiepan geleverd. Deze aluminiumschaal is uitneembaar en makkelijk te stapelen. Ideaal als je de inhoud nog een dag (of meerdere dagen) in de koelkast wil bewaren! Ook is het mogelijk om enkel de inhoud van een Kippiepan te bestellen. Je krijgt dan enkel de aluminium inlegschaal met de hapjes en/of maaltijden.&nbsp;</span><br></div><div><br></div><div><b>Ook exclusief bij Kippie:</b> de borg van een Kippiepan is slechts 15 euro.</div><div>Voor deze 15 euro kun je de pan ook thuis houden. Je hoeft de pan niet per se in te leveren bij de winkel.</div><div><i>De elektrische pannen zijn inclusief stekker, deksel, aluminiumschaal en plastic deksel. Het vermogen van de reguliere Kippiepan is 1400 Watt.</i></div>",
      "product_custom_field_button_active": true,
      "custom_product_sorting_priority_number": 1,
      "product_custom_field_indication_active": true,
      "product_custom_field_indication_left_icon": "fish",
      "product_custom_field_indication_left_text": "66 hapjes",
      "product_custom_field_indication_right_icon": "person",
      "product_custom_field_indication_right_text": "8 personen",
      "product_custom_field_button_short_description": "De snackpan is gevuld met 65 verschillende kiphapjes. Hotwings, snacks, borrelhapjes, oosterse kiphapjes, mini satéstokken en kipgehakt ballen zijn allemaal te vinden in deze heerlijke snackpan. Tip: een feestje met meer dan 10 personen? Probeer dan de XL versie van deze pan eens! Welke hapjes",
      "borg_product_tag": "BORG1",
      "available_deliveries_label": "Delivery en Pickup"
    },
    "translated": {
      "name": "Snackpan",
      "description": "<div><b>Welke hapjes vind je in de snackpan van Kippie?</b></div><div>- Kipgehaktballetjes (gemarineerd met ketjapmarinade)</div><div>- Mini kipsatéstokjes (gemarineerd met een kruidige marinade met een lichte kerrie/knoflooksmaak)</div><div>- Pittige kipkluifjes (kluifjes gemarineerd met een pittige assum marinade)</div><div>- Zoete kipkluifjes (kluifjes gemarineerd met een Japanse ketjapmarinade)</div><div>- Naturel borrelhapjes (naturel gekruide kipkluifjes)</div><div><br></div><div><b>Allergenen:</b></div><div>De snackpan bevat de allergenen gluten, soja, selderij, mosterd en ei. (Let op bij afhalen dat er enkele vestigingen zijn die de balletjes standaard in pindasaus verkopen, vraag dit zonodig na bij de winkel!)</div><div><br></div><div><i>Bij iedere Kippiepan wordt 15 euro borg gerekend. Bij het inleveren van de pan krijg je dit bedrag direct terug! Je kunt er ook voor kiezen om de pan te houden en een volgende keer enkel de inhoud te bestellen.</i></div>",
      "customFields": {
        "borg_id": "7bd89b026b5642dda7ba8a27433dcec9",
        "usp_active": true,
        "borg_active": true,
        "usp_content": "Best verkocht!",
        "borg_required": "1",
        "custom_delivery": "delivery",
        "product_custom_field_title": "Gebruiksaanwijzing",
        "product_custom_field_video": "https://youtu.be/-JMAj6dgGso",
        "product_custom_field_usp_list": "{\"0\":{\"icon\":\"egg\",\"usp\":\"Geen eieren\"},\"1\":{\"icon\":\"check\",\"usp\":\"Lekkerste Kip van Nederland\"},\"2\":{\"icon\":\"check\",\"usp\":\"Lekkerste Kip van Nederland\"},\"3\":{\"icon\":\"check\",\"usp\":\"Lekkerste Kip van Nederland\"}}",
        "custom_delivery_available_fields": [
          "757b981b517e4cb59e63b2dbfad46cf9",
          "a4139c276ad24bf1ab51cebce3864376"
        ],
        "product_custom_field_button_text": "Meer Info",
        "product_custom_field_text_content": "<b>Hoe werkt de Kippiepan?</b><div>De Kippiepan is een pan die aangesloten kan worden op netstroom om de inhoud op te warmen. Er zijn verschillende varianten verkrijgbaar via onze webshop en in al onze winkels. Voor de elektrische pannen wordt borg betaalt, maar klanten kunnen er ook voor kiezen om de pan thuis te houden voor dat bedrag.</div><div>De Kippiepan is erg eenvoudig in gebruik. Na het verwijderen van de doorzichtige plastic deksel, steek je de stekker van de pan in het stopcontact. Op stand nummer 2 laat je de pan ongeveer 30 minuten opwarmen. Let er op dat je de inhoud af en toe goed doorroert of omschept. Dit om aanbakken te voorkomen. Absoluut geen gedoe of stress in de keuken. Klaar? Aanschuiven maar!</div><div><i style=\"letter-spacing: 0px;\">Tip: wordt de inhoud van de Kippiepan niet snel genoeg warm? Zet de thermostaat gerust een stand hoger. Blijf wel goed omroeren of omscheppen om aanbakken te voorkomen.</i><br></div><div><i style=\"letter-spacing: 0px;\"><br></i></div><div><b style=\"letter-spacing: 0px;\">Heb je een losse aluminium schaal met inhoud besteld? Deze kan ook in de oven worden opgewarmd! Haal de plastic deksel van de schaal af en plaats de aluminiumschaal in een voorverwarmde oven. Ongeveer 15 tot 20 minuten op 180 graden is voldoende.</b></div><div><b style=\"letter-spacing: 0px;\"><br></b></div><div><b style=\"letter-spacing: 0px;\">Exclusief bij Kippie:</b><span style=\"letter-spacing: 0px;\"> de inhoud van iedere Kippiepan wordt in een aluminiumschaal met plastic deksel in de Kippiepan geleverd. Deze aluminiumschaal is uitneembaar en makkelijk te stapelen. Ideaal als je de inhoud nog een dag (of meerdere dagen) in de koelkast wil bewaren! Ook is het mogelijk om enkel de inhoud van een Kippiepan te bestellen. Je krijgt dan enkel de aluminium inlegschaal met de hapjes en/of maaltijden.&nbsp;</span><br></div><div><br></div><div><b>Ook exclusief bij Kippie:</b> de borg van een Kippiepan is slechts 15 euro.</div><div>Voor deze 15 euro kun je de pan ook thuis houden. Je hoeft de pan niet per se in te leveren bij de winkel.</div><div><i>De elektrische pannen zijn inclusief stekker, deksel, aluminiumschaal en plastic deksel. Het vermogen van de reguliere Kippiepan is 1400 Watt.</i></div>",
        "product_custom_field_button_active": true,
        "custom_product_sorting_priority_number": 1,
        "product_custom_field_indication_active": true,
        "product_custom_field_indication_left_icon": "fish",
        "product_custom_field_indication_left_text": "66 hapjes",
        "product_custom_field_indication_right_icon": "person",
        "product_custom_field_indication_right_text": "8 personen",
        "product_custom_field_button_short_description": "De snackpan is gevuld met 65 verschillende kiphapjes. Hotwings, snacks, borrelhapjes, oosterse kiphapjes, mini satéstokken en kipgehakt ballen zijn allemaal te vinden in deze heerlijke snackpan. Tip: een feestje met meer dan 10 personen? Probeer dan de XL versie van deze pan eens! Welke hapjes",
        "borg_product_tag": "BORG1",
        "available_deliveries_label": "Delivery en Pickup"
      }
    },
    "id": "3e114fa71d404f1aaae65a73994002da",
    "apiAlias": "product"
  },
}
```

As u can see i have two customFields objects exactly the same.
Is it possible to set customFields bback to the way they where in PWA 0.8.2 So i don't have to customize the apiDefaultParams. I think the customFields are a pretty important thing for shopware 6 and pwa.

### PR DESCRIPTION
**Pull request by meeshoogendoorn**
## Changes
Closes #1539 

### Checklist

- [x] the [list of features](docs/guide/FEATURELIST.md) is updated (if it's a feature and it's relevant)
- [x] I followed [contributing](https://github.com/DivanteLtd/shopware-pwa/blob/master/CONTRIBUTING.md) guidelines

### CODE REVIEW

**Comment by meeshoogendoorn** [comment]
@mkucmus I added the computed to the useAddToCart Composable. I runned yarn lint before pushing with the command `yarn lint` from the project but he forrmatted some more files. is that okey? I can't find any prettierrc file in the project also?

**Comment by patzick** [comment]
Thanks, @meeshoogendoorn, great to see your contribution! 💪 

It's okay to run `yarn lint`, there is a rule linting all files before commit, but the linter wasn't running on all files in a long time. I cleared it on the master branch to see real changes in here.
Created check-in #1553 to see if GH actions are passing. The one with composables is failing, as you haven't refreshed API docs.

Please run `yarn build -t` locally and commit markdown changes that will be automatically created :)

Overall all looks great, so I'll merge that right after fixing CI!

**Comment by meeshoogendoorn** [comment]
@patzick It's fixed 👍

**Review by patzick — APPROVED** [review]
Perfect 👌  thank you for your contribution! We're waiting for the next ones 🚀

**Pull request merged**
