### PR TITLE
docs: migration guide for next release & small corrections

### PR DESCRIPTION
**Pull request by mkucmus**
## Changes

- new structure of docs regarding upgrade
- small corrections regarding CLI

### Checklist

- [ ] the [list of features](docs/guide/FEATURELIST.md) is updated (if it's a feature and it's relevant)
- [ ] I followed [contributing](https://github.com/DivanteLtd/shopware-pwa/blob/master/CONTRIBUTING.md) guidelines

### CODE REVIEW

**Review by elkmod — APPROVED** [review]

**Comment by develth** [comment]
Hi, 

thanks for that Guide!
I followed the 0.6.x to 0.7.x but after a build and starting dev i just get a

`Cannot destructure property 'languageId' of 'domainConfig' as it is undefined.`

Added following to shopware-pwa.config.js - localhost is also available in shopware SalesChannel

`  pwaHost: "http://localhost",
  fallbackDomain: "/default",`

Thx!

**Comment by mkucmus** [comment]
> Hi,
> 
> thanks for that Guide!
> I followed the 0.6.x to 0.7.x but after a build and starting dev i just get a
> 
> `Cannot destructure property 'languageId' of 'domainConfig' as it is undefined.`
> 
> Added following to shopware-pwa.config.js - localhost is also available in shopware SalesChannel
> 
> ` pwaHost: "http://localhost", fallbackDomain: "/default",`
> 
> Thx!

Hi!  thanks for the first official test :+1: 

could you please check whether there is a file `.shopware-pwa/sw-plugins/domains.json`, containing domains data?
if not, please run `npx @shopware-pwa/cli@canary domains` command. Otherwise we would need more details and try to reproduce it anyway :)

**Comment by develth** [comment]
I did a whole init and afterwards, while reading the docs, a separate domains. Both where successful (The Commands running).
The `.shopware-pwa/sw-plugins/domains.json` exists, but is empty. When doing a `console.log(router)` `.nuxst/domains.js` at e.g. line 56 it is also empty

**Comment by develth** [comment]
ERROR-40

Had `https://localhost` in Domain Config, after changing it to `http://localhost` it worked. 

Thanks!

**Comment by mkucmus** [comment]
> ERROR-40
> 
> Had `https://localhost` in Domain Config, after changing it to `http://localhost` `.shopware-pwa/sw-plugins/domains.json` was filled
> 
> Thanks!

oh, so that was it. We should better notify the user about such circumstances because we do filter the domains depending on the pwaDomain config... empty domains.json should throw an error for sure. Thanks for that insight! @develth!

**Pull request merged**
